from datetime import date

from ..config import CompetitionEditionConfig, HistoricalMatchSource


PREMIER_LEAGUE_2026_27 = CompetitionEditionConfig(
    competition_slug="premier-league",
    competition_display_name="Premier League",
    competition_display_name_key="competitions.premierLeague.name",
    edition_slug="2026-27",
    edition_display_name="Premier League 2026-27",
    edition_display_name_key="competitions.editions.premierLeague2026_27.name",
    configuration_revision="2026-07-26.1",
    format="league",
    capabilities=("table", "fixtures", "predictions", "markets"),
    current_from=date(2026, 7, 1),
    current_until=date(2027, 6, 30),
    fixture_date_from=date(2026, 8, 1),
    fixture_date_until=date(2027, 5, 31),
    points_for_win=3,
    points_for_draw=1,
    table_tiebreakers=("points", "goal_difference", "goals_scored"),
    outcome_bands=(
        ("champions_league", 1, 4),
        ("europa_league", 5, 5),
        ("conference_league", 6, 6),
        ("relegation", 18, 20),
    ),
    participating_team_ids=(
        "arsenal",
        "aston-villa",
        "bournemouth",
        "brentford",
        "brighton-and-hove-albion",
        "chelsea",
        "coventry-city",
        "crystal-palace",
        "everton",
        "fulham",
        "hull-city",
        "ipswich-town",
        "leeds-united",
        "liverpool",
        "manchester-city",
        "manchester-united",
        "newcastle-united",
        "nottingham-forest",
        "sunderland",
        "tottenham-hotspur",
    ),
    provider_competition_id="eng.1",
    provider_season="2026",
    provider_team_mappings=(
        ("arsenal", "359"),
        ("aston-villa", "362"),
        ("bournemouth", "349"),
        ("brentford", "337"),
        ("brighton-and-hove-albion", "331"),
        ("chelsea", "363"),
        ("coventry-city", "388"),
        ("crystal-palace", "384"),
        ("everton", "368"),
        ("fulham", "370"),
        ("hull-city", "306"),
        ("ipswich-town", "373"),
        ("leeds-united", "357"),
        ("liverpool", "364"),
        ("manchester-city", "382"),
        ("manchester-united", "360"),
        ("newcastle-united", "361"),
        ("nottingham-forest", "393"),
        ("sunderland", "366"),
        ("tottenham-hotspur", "367"),
    ),
    live_refresh_seconds=30,
    kickoff_window_refresh_seconds=120,
    in_season_refresh_seconds=900,
    off_season_refresh_seconds=86400,
    live_stale_seconds=300,
    kickoff_window_stale_seconds=900,
    in_season_stale_seconds=86400,
    historical_match_sources=(
        HistoricalMatchSource("eng.1", "2024", date(2024, 8, 1), date(2025, 5, 31)),
        HistoricalMatchSource("eng.1", "2025", date(2025, 8, 1), date(2026, 5, 31)),
        HistoricalMatchSource("eng.2", "2025", date(2025, 8, 1), date(2026, 5, 31)),
    ),
    promoted_team_ids=("coventry-city", "hull-city", "ipswich-town"),
)
