<template>
  <div class="atlas-lab">
    <header class="lab-header">
      <div><p>SoccerOctopus / client direction</p><h1>Tournament Atlas across the portal.</h1><span>The selected competition-first system applied to five existing workflows.</span></div>
      <div class="lab-actions"><div class="mode-control" role="group" aria-label="Preview theme"><button type="button" :class="{ active: theme === 'light' }" @click="setTheme('light')"><Sun :size="14" /> Light</button><button type="button" :class="{ active: theme === 'dark' }" @click="setTheme('dark')"><Moon :size="14" /> Dark</button></div><router-link to="/design-lab">Back to variations <ArrowUpRight :size="14" /></router-link></div>
    </header>

    <nav class="screen-tabs" aria-label="Atlas screens"><button v-for="screen in screens" :key="screen.key" type="button" :class="{ active: activeScreen === screen.key }" @click="activeScreen = screen.key"><span>{{ screen.short }}</span>{{ screen.label }}</button></nav>

    <section :class="['atlas-portal', `portal-${theme}`]">
      <header class="portal-nav">
        <router-link to="/" class="brand"><span>SO</span><strong>SoccerOctopus</strong></router-link>
        <div class="competition"><small>Competition workspace</small><strong>FIFA World Cup 2026</strong></div>
        <nav><button v-for="screen in screens" :key="screen.key" type="button" :class="{ active: activeScreen === screen.key }" @click="activeScreen = screen.key">{{ screen.nav }}</button></nav>
        <span class="profile">RO</span>
      </header>

      <main class="portal-main">
        <section v-if="activeScreen === 'home'" class="portal-screen home-screen">
          <div class="home-hero"><div class="hero-copy"><p class="kicker">FIFA World Cup 2026</p><h2>Every route.<br /><i>One competition.</i></h2><span>48 teams across 12 groups in the United States, Canada, and Mexico.</span><button class="primary-action" type="button" @click="activeScreen = 'predict'">Predict a match <ArrowRight :size="15" /></button></div><div class="hero-year" aria-hidden="true">26</div><div class="home-metrics"><div><strong>48</strong><span>teams</span></div><div><strong>12</strong><span>groups</span></div><div><strong>104</strong><span>matches</span></div></div></div>
          <div class="home-modules"><button type="button" @click="activeScreen = 'groups'"><span>Browse</span><strong>WC 2026 groups</strong><small>Teams, ELO, and rank</small><ArrowUpRight :size="14" /></button><button type="button" @click="activeScreen = 'predict'"><span>Analyse</span><strong>Predict a match</strong><small>Probabilities and scoreline</small><ArrowUpRight :size="14" /></button><button type="button" @click="activeScreen = 'tournament'"><span>Simulate</span><strong>Full tournament</strong><small>Groups to the final</small><ArrowUpRight :size="14" /></button><button type="button" @click="activeScreen = 'markets'"><span>Generate</span><strong>Prediction markets</strong><small>Match props and futures</small><ArrowUpRight :size="14" /></button></div>
          <section class="swarm-strip"><div class="section-title"><span>Swarm inputs</span><h3>Five agents, one result</h3></div><div class="agent-tile" v-for="agent in agents" :key="agent.code"><span>{{ agent.code }}</span><strong>{{ agent.name }}</strong><small>{{ agent.detail }}</small><b>{{ agent.weight }}</b></div></section>
        </section>

        <section v-else-if="activeScreen === 'groups'" class="portal-screen groups-screen">
          <div class="screen-heading"><div><p class="kicker">Group stage</p><h2>12 groups.<br />48 teams.</h2><span>Team strength at a glance, ordered by ELO.</span></div><div class="group-key"><span>Four representative groups</span><span>Representative rank and ELO values</span></div></div>
          <div class="groups-layout"><article v-for="group in groups" :key="group.label" class="group-block"><header><strong>{{ group.label }}</strong><span>Team</span><span>ELO</span><span>Rank</span></header><div v-for="(team, index) in group.teams" :key="team.name" class="group-team"><span>{{ index + 1 }}</span><strong><i :class="['crest', team.tone]">{{ team.code }}</i>{{ team.name }}</strong><b>{{ team.elo }}</b><small>#{{ team.rank }}</small></div></article></div>
        </section>

        <section v-else-if="activeScreen === 'predict'" class="portal-screen predict-screen">
          <div class="predict-heading"><div><p class="kicker">Predict a match</p><h2>Brazil <i>vs.</i> Germany</h2></div><div class="match-selectors"><label>Home team<button type="button">Brazil <ChevronDown :size="14" /></button></label><label>Away team<button type="button">Germany <ChevronDown :size="14" /></button></label><label>Stage<button type="button">Group stage <ChevronDown :size="14" /></button></label><button class="primary-action" type="button">Run prediction <Sparkles :size="14" /></button></div></div>
          <div class="prediction-board"><div class="score-billboard"><span>Most likely score</span><strong>2:1</strong><small>Brazil win</small><b>78.4% swarm confidence</b></div><div class="probability-board"><div v-for="outcome in outcomes" :key="outcome.label"><span>{{ outcome.label }}</span><strong>{{ outcome.value }}</strong><i><b :style="{ width: outcome.value }"></b></i></div></div><div class="consensus-copy"><span>Swarm consensus</span><h3>Brazil carries the stronger model signal.</h3><p>ELO, recent form, and tactical profile outweigh a cautious video-intelligence prediction.</p><button type="button">Open full analysis <ArrowRight :size="14" /></button></div></div>
          <div class="prediction-evidence"><div><span>Expected goals</span><strong>2.08 / 1.16</strong></div><div><span>Top score probability</span><strong>2-1 / 14.8%</strong></div><div><span>Agent agreement</span><strong>4 of 4 favour Brazil</strong></div></div>
        </section>

        <section v-else-if="activeScreen === 'tournament'" class="portal-screen tournament-screen">
          <div class="tournament-hero"><div><p class="kicker">Full tournament simulation</p><h2>From groups<br /><i>to the final.</i></h2><p>Official results stay fixed. Only the remaining fixtures are predicted.</p><button class="primary-action" type="button">Run simulation <ArrowRight :size="14" /></button></div><div class="tournament-year" aria-hidden="true">26</div><div class="podium"><span>Latest model projection</span><div><article><small>Runner-up</small><strong>France</strong></article><article class="champion"><small>Champion</small><strong>Argentina</strong><b>22.8% final win probability</b></article><article><small>Third</small><strong>Brazil</strong></article></div></div></div>
          <div class="atlas-bracket"><div v-for="round in rounds" :key="round.label" class="round"><header><strong>{{ round.label }}</strong><span>{{ round.count }}</span></header><div v-for="match in round.matches" :key="match.home" class="match"><span :class="{ winner: match.winner === match.home }">{{ match.home }}</span><b>{{ match.score }}</b><span :class="{ winner: match.winner === match.away }">{{ match.away }}</span><small>Predicted</small></div></div></div>
        </section>

        <section v-else class="portal-screen markets-screen">
          <div class="screen-heading markets-heading"><div><p class="kicker">Prediction markets</p><h2>Questions from<br />the model.</h2><span>Ready-to-list contracts for Kalshi and Polymarket.</span></div><div class="market-mode"><button type="button" :class="{ active: marketMode === 'match' }" @click="marketMode = 'match'">Match markets</button><button type="button" :class="{ active: marketMode === 'future' }" @click="marketMode = 'future'">Tournament futures</button></div></div>
          <div class="market-overview"><div class="market-feature"><span>{{ marketMode === 'match' ? 'Brazil vs. Germany' : 'World Cup 2026' }}</span><strong>{{ marketMode === 'match' ? '64.2%' : '22.8%' }}</strong><small>{{ marketMode === 'match' ? 'Brazil win probability' : 'Argentina champion probability' }}</small><button class="primary-action" type="button">Generate markets <ArrowRight :size="14" /></button></div><div class="market-table"><header><span>Type</span><span>Question</span><span>Fair value</span><span></span></header><div v-for="market in activeMarkets" :key="market.question"><span>{{ market.kind }}</span><strong>{{ market.question }}</strong><b>{{ market.price }}</b><ArrowUpRight :size="14" /></div></div></div>
        </section>
      </main>
    </section>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ArrowRight, ArrowUpRight, ChevronDown, Moon, Sparkles, Sun } from '@lucide/vue'

const screens = [{ key: 'home', short: '01', label: 'Home overview', nav: 'Home' }, { key: 'groups', short: '02', label: 'Groups', nav: 'Groups' }, { key: 'predict', short: '03', label: 'Predict match', nav: 'Predict' }, { key: 'tournament', short: '04', label: 'Tournament', nav: 'Tournament' }, { key: 'markets', short: '05', label: 'Markets', nav: 'Markets' }]
const agents = [{ code: 'ST', name: 'Statistical', detail: 'ELO / Poisson / SofaScore', weight: '1.8x' }, { code: 'VI', name: 'Video intelligence', detail: 'YouTube / sentiment', weight: '1.0x' }, { code: 'RF', name: 'Recent form', detail: 'Last 10 / trajectory', weight: '1.3x' }, { code: 'TA', name: 'Tactical', detail: 'Style matchup matrix', weight: '1.2x' }, { code: 'AG', name: 'Aggregator', detail: 'Consensus / narrative', weight: '-' }]
const groups = [
  { label: 'Group A', teams: [{ name: 'Mexico', code: 'MX', tone: 'green', elo: '1855', rank: '18' }, { name: 'South Korea', code: 'KR', tone: 'red', elo: '1850', rank: '22' }, { name: 'Czechia', code: 'CZ', tone: 'blue', elo: '1835', rank: '36' }, { name: 'South Africa', code: 'ZA', tone: 'gold', elo: '1775', rank: '60' }] },
  { label: 'Group C', teams: [{ name: 'Brazil', code: 'BR', tone: 'green', elo: '2050', rank: '4' }, { name: 'Morocco', code: 'MA', tone: 'red', elo: '1890', rank: '14' }, { name: 'Scotland', code: 'SC', tone: 'blue', elo: '1820', rank: '43' }, { name: 'Haiti', code: 'HT', tone: 'blue', elo: '1720', rank: '83' }] },
  { label: 'Group F', teams: [{ name: 'Netherlands', code: 'NL', tone: 'red', elo: '2005', rank: '8' }, { name: 'Sweden', code: 'SE', tone: 'blue', elo: '1900', rank: '26' }, { name: 'Japan', code: 'JP', tone: 'red', elo: '1895', rank: '15' }, { name: 'Tunisia', code: 'TN', tone: 'red', elo: '1800', rank: '45' }] },
  { label: 'Group H', teams: [{ name: 'Spain', code: 'ES', tone: 'red', elo: '2045', rank: '3' }, { name: 'Uruguay', code: 'UY', tone: 'blue', elo: '1925', rank: '19' }, { name: 'Saudi Arabia', code: 'SA', tone: 'green', elo: '1805', rank: '56' }, { name: 'Cape Verde', code: 'CV', tone: 'blue', elo: '1760', rank: '79' }] },
]
const outcomes = [{ label: 'Brazil win', value: '64.2%' }, { label: 'Draw', value: '20.7%' }, { label: 'Germany win', value: '15.1%' }]
const rounds = [{ label: 'Round of 32', count: '16 matches', matches: [{ home: 'Argentina', away: 'Senegal', score: '2-0', winner: 'Argentina' }, { home: 'Brazil', away: 'Australia', score: '2-1', winner: 'Brazil' }] }, { label: 'Quarter-finals', count: '4 matches', matches: [{ home: 'Argentina', away: 'Portugal', score: '1-0', winner: 'Argentina' }, { home: 'Brazil', away: 'France', score: '2-1', winner: 'Brazil' }] }, { label: 'Semi-finals', count: '2 matches', matches: [{ home: 'Argentina', away: 'Brazil', score: '2-1', winner: 'Argentina' }] }, { label: 'Final', count: '1 match', matches: [{ home: 'Argentina', away: 'Spain', score: '2-1', winner: 'Argentina' }] }]
const matchMarkets = [{ kind: 'MATCH', question: 'Will Brazil win against Germany?', price: '64.2c' }, { kind: 'SCORE', question: 'Will the most likely score be 2-1?', price: '14.8c' }, { kind: 'TOTAL', question: 'Will the match have over 2.5 goals?', price: '57.1c' }]
const futureMarkets = [{ kind: 'CHAMPION', question: 'Will Argentina win the tournament?', price: '22.8c' }, { kind: 'FINAL', question: 'Will Brazil reach the final?', price: '41.4c' }, { kind: 'GROUP', question: 'Will Mexico win Group A?', price: '60.0c' }]
const activeScreen = ref('home')
const marketMode = ref('match')
const theme = ref('light')
const activeMarkets = computed(() => marketMode.value === 'match' ? matchMarkets : futureMarkets)
function setTheme(value) { theme.value = value; window.localStorage?.setItem('socceroctopus-atlas-theme', value) }
onMounted(() => { const saved = window.localStorage?.getItem('socceroctopus-atlas-theme'); theme.value = saved === 'light' || saved === 'dark' ? saved : window.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light' })
</script>

<style scoped>
.atlas-lab { --lab-ink:#24201c; --lab-muted:#746d64; --lab-accent:#1f7771; background:#f8f5ee; display:flex; flex-direction:column; gap:24px; margin:-32px; min-height:calc(100vh - 64px); padding:52px 32px 40px; }.lab-header,.screen-tabs,.atlas-portal{margin:0 auto;max-width:1280px;width:100%}.lab-header{align-items:end;display:flex;gap:40px;justify-content:space-between}.lab-header p,.kicker{color:var(--lab-accent);font:800 9px 'SFMono-Regular',monospace;letter-spacing:.1em;margin:0 0 9px;text-transform:uppercase}.lab-header h1{color:var(--lab-ink);font:800 clamp(40px,5vw,68px)/.92 'Arial Narrow',sans-serif;letter-spacing:-.06em;margin:0;max-width:730px}.lab-header>div>span{color:var(--lab-muted);display:block;font-size:14px;margin-top:14px}.lab-actions{align-items:end;display:flex;flex-direction:column;gap:10px}.mode-control{background:#e6e1d7;display:flex;padding:3px}.mode-control button{align-items:center;background:transparent;border:0;color:#7d756b;display:inline-flex;font-size:10px;font-weight:700;gap:5px;padding:8px 10px}.mode-control button.active{background:#fff;color:var(--lab-ink)}.lab-actions a{align-items:center;color:var(--lab-muted);display:inline-flex;font-size:11px;font-weight:700;gap:5px;text-decoration:none}.screen-tabs{display:flex;gap:7px;overflow-x:auto}.screen-tabs button{background:transparent;border:1px solid transparent;color:#756e65;display:inline-flex;flex:0 0 auto;font-size:11px;font-weight:700;gap:7px;padding:9px 11px}.screen-tabs button span{color:#9d958a;font:800 8px 'SFMono-Regular',monospace}.screen-tabs button.active{background:#fff;border-color:#ddd5c9;color:#24201c;box-shadow:0 4px 14px rgba(56,45,33,.07)}
.atlas-portal{--at-bg:#eee9df;--at-surface:#f8f4eb;--at-ink:#24201c;--at-muted:#7d736a;--at-line:#d2c7b8;--at-accent:#1f7771;--at-soft:#d8e7e0;background:var(--at-bg);border:1px solid #d0c6b8;color:var(--at-ink);min-height:760px;overflow:hidden}.atlas-portal.portal-dark{--at-bg:#121515;--at-surface:#1b201f;--at-ink:#edf1e9;--at-muted:#9ba39d;--at-line:#3b4641;--at-accent:#6db1a0;--at-soft:#25443e;border-color:#3b4641}.portal-nav{align-items:center;border-bottom:1px solid var(--at-line);display:grid;gap:28px;grid-template-columns:auto auto 1fr auto;min-height:68px;padding:0 35px}.brand{align-items:center;color:var(--at-ink);display:inline-flex;font:800 14px 'Arial Narrow',sans-serif;gap:9px;text-decoration:none}.brand span{align-items:center;background:var(--at-accent);color:#fff;display:inline-flex;font:800 9px 'SFMono-Regular',monospace;height:27px;justify-content:center;width:27px}.competition{border-left:1px solid var(--at-line);display:flex;flex-direction:column;gap:4px;padding-left:18px}.competition small{color:var(--at-muted);font-size:8px}.competition strong{font:800 10px 'SFMono-Regular',monospace}.portal-nav nav{display:flex;gap:21px;justify-content:end}.portal-nav nav button{background:transparent;border:0;color:var(--at-muted);font-size:10px;font-weight:700}.portal-nav nav button.active{color:var(--at-accent)}.profile{align-items:center;background:var(--at-surface);border:1px solid var(--at-line);display:inline-flex;font:800 8px 'SFMono-Regular',monospace;height:28px;justify-content:center;width:28px}.portal-main{margin:auto;max-width:1210px;padding:0 35px 46px}.primary-action{align-items:center;background:var(--at-accent);border:0;color:#fff;display:inline-flex;font-size:9px;font-weight:800;gap:7px;padding:11px 13px;white-space:nowrap}.primary-action:hover{filter:brightness(1.08);transform:translateY(-1px)}
.home-hero{border-bottom:1px solid var(--at-line);display:grid;grid-template-columns:1fr .9fr;min-height:330px;overflow:hidden;padding:47px 0 36px;position:relative}.hero-copy{position:relative;z-index:1}.hero-copy h2,.screen-heading h2,.predict-heading h2,.tournament-hero h2{font:800 clamp(52px,7vw,88px)/.83 'Arial Narrow',sans-serif;letter-spacing:-.075em;margin:0}.hero-copy h2 i,.predict-heading h2 i,.tournament-hero h2 i{color:var(--at-accent);font-style:normal}.hero-copy>span,.screen-heading>div>span{color:var(--at-muted);display:block;font-size:11px;line-height:1.5;margin-top:19px;max-width:42ch}.hero-copy .primary-action{margin-top:23px}.hero-year{align-self:center;color:var(--at-soft);font:900 280px/.7 'Arial Narrow',sans-serif;letter-spacing:-.16em;margin-left:-45px}.home-metrics{background:var(--at-surface);border-left:1px solid var(--at-line);border-top:1px solid var(--at-line);bottom:0;display:grid;grid-template-columns:repeat(3,1fr);padding:16px 20px;position:absolute;right:0;width:45%}.home-metrics div{display:flex;flex-direction:column;gap:3px}.home-metrics strong{color:var(--at-accent);font:800 16px 'SFMono-Regular',monospace}.home-metrics span{color:var(--at-muted);font-size:8px}.home-modules{border-bottom:1px solid var(--at-line);display:grid;grid-template-columns:repeat(4,1fr)}.home-modules button{background:transparent;border:0;border-right:1px solid var(--at-line);color:var(--at-ink);display:grid;gap:5px;min-height:100px;padding:18px 16px;position:relative;text-align:left}.home-modules button:last-child{border-right:0}.home-modules button:hover{background:var(--at-soft)}.home-modules span{color:var(--at-accent);font:800 8px 'SFMono-Regular',monospace;text-transform:uppercase}.home-modules strong{font:800 16px 'Arial Narrow',sans-serif}.home-modules small{color:var(--at-muted);font-size:8px}.home-modules svg{color:var(--at-accent);position:absolute;right:15px;top:17px}.swarm-strip{display:grid;grid-template-columns:1.15fr repeat(5,1fr);padding-top:27px}.section-title h3{font:800 22px 'Arial Narrow',sans-serif;margin:6px 0}.section-title>span{color:var(--at-accent);font:800 8px 'SFMono-Regular',monospace;text-transform:uppercase}.agent-tile{border-left:1px solid var(--at-line);display:grid;gap:4px;grid-template-columns:25px 1fr;padding:3px 11px}.agent-tile>span{color:var(--at-accent);font:800 8px 'SFMono-Regular',monospace}.agent-tile strong{font-size:9px}.agent-tile small{color:var(--at-muted);font:7px 'SFMono-Regular',monospace;grid-column:2}.agent-tile b{color:var(--at-accent);font:800 10px 'SFMono-Regular',monospace;grid-column:2}
.screen-heading{align-items:end;border-bottom:1px solid var(--at-line);display:flex;justify-content:space-between;padding:47px 0 30px}.group-key{align-items:flex-end;color:var(--at-muted);display:flex;flex-direction:column;font:8px 'SFMono-Regular',monospace;gap:7px}.group-key i{background:var(--at-accent);display:inline-block;height:6px;margin-right:5px;width:6px}.groups-layout{display:grid;gap:24px 18px;grid-template-columns:repeat(2,1fr);padding-top:29px}.group-block{border-left:2px solid var(--at-line);padding-left:13px}.group-block header,.group-team{display:grid;gap:9px;grid-template-columns:48px 1fr 55px 42px}.group-block header{border-bottom:1px solid var(--at-line);color:var(--at-muted);font:8px 'SFMono-Regular',monospace;padding:0 0 8px}.group-block header strong{color:var(--at-accent)}.group-team{align-items:center;border-bottom:1px solid var(--at-line);min-height:42px}.group-team>span,.group-team>b,.group-team>small{color:var(--at-muted);font:9px 'SFMono-Regular',monospace}.group-team>strong{align-items:center;display:flex;font-size:10px;gap:7px}.group-team.qualifying{background:color-mix(in srgb,var(--at-soft) 45%,transparent)}.crest{align-items:center;color:#fff;display:inline-flex;font:800 7px 'SFMono-Regular',monospace;height:18px;justify-content:center;width:22px}.crest.green{background:#4d7654}.crest.red{background:#a85750}.crest.blue{background:#4c719b}.crest.gold{background:#9e8941}
.predict-heading{align-items:end;border-bottom:1px solid var(--at-line);display:grid;gap:28px;grid-template-columns:1fr 1.25fr;padding:47px 0 29px}.match-selectors{align-items:end;display:grid;gap:8px;grid-template-columns:1fr 1fr 1fr auto}.match-selectors label{color:var(--at-muted);display:flex;flex-direction:column;font:8px 'SFMono-Regular',monospace;gap:5px}.match-selectors label button{align-items:center;background:var(--at-surface);border:1px solid var(--at-line);color:var(--at-ink);display:flex;font-size:9px;font-weight:800;justify-content:space-between;min-width:0;padding:9px 8px}.prediction-board{display:grid;grid-template-columns:.75fr .9fr 1.15fr}.prediction-board>div{border-right:1px solid var(--at-line);padding:29px 24px}.prediction-board>div:last-child{border-right:0}.score-billboard{align-items:center;background:var(--at-soft);display:flex;flex-direction:column;justify-content:center;text-align:center}.score-billboard>span,.score-billboard>small{color:var(--at-muted);font-size:8px}.score-billboard>strong{font:800 57px 'SFMono-Regular',monospace;letter-spacing:-.12em;margin:8px 0 3px}.score-billboard>b{color:var(--at-accent);font:800 8px 'SFMono-Regular',monospace;margin-top:11px}.probability-board{display:flex;flex-direction:column;gap:15px}.probability-board>div{display:grid;gap:6px;grid-template-columns:1fr auto}.probability-board span{color:var(--at-muted);font-size:9px}.probability-board strong{font:800 10px 'SFMono-Regular',monospace}.probability-board i{background:var(--at-soft);grid-column:1/-1;height:4px}.probability-board b{background:var(--at-accent);display:block;height:100%}.consensus-copy>span{color:var(--at-accent);font:800 8px 'SFMono-Regular',monospace;text-transform:uppercase}.consensus-copy h3{font:800 23px 'Arial Narrow',sans-serif;letter-spacing:-.04em;margin:8px 0}.consensus-copy p{color:var(--at-muted);font-size:9px;line-height:1.5}.consensus-copy button{align-items:center;background:transparent;border:0;color:var(--at-accent);display:inline-flex;font-size:9px;font-weight:800;gap:5px;margin-top:10px;padding:0}.prediction-evidence{border-bottom:1px solid var(--at-line);border-top:1px solid var(--at-line);display:grid;grid-template-columns:repeat(3,1fr);padding:17px 0}.prediction-evidence div{display:flex;flex-direction:column;gap:5px}.prediction-evidence span{color:var(--at-muted);font:8px 'SFMono-Regular',monospace}.prediction-evidence strong{font-size:10px}
.tournament-hero{border-bottom:1px solid var(--at-line);display:grid;grid-template-columns:1fr .9fr;min-height:310px;overflow:hidden;padding:46px 0 36px;position:relative}.tournament-hero>div:first-child{position:relative;z-index:1}.tournament-hero p:not(.kicker){color:var(--at-muted);font-size:10px;line-height:1.5;max-width:42ch}.tournament-hero .primary-action{margin-top:18px}.tournament-year{align-self:center;color:var(--at-soft);font:900 270px/.7 'Arial Narrow',sans-serif;letter-spacing:-.15em;margin-left:-35px}.podium{background:var(--at-surface);border-left:1px solid var(--at-line);border-top:1px solid var(--at-line);bottom:0;padding:15px 18px;position:absolute;right:0;width:46%}.podium>span{color:var(--at-muted);font:8px 'SFMono-Regular',monospace;text-transform:uppercase}.podium>div{align-items:end;display:grid;gap:10px;grid-template-columns:1fr 1.15fr 1fr;margin-top:13px}.podium article{display:flex;flex-direction:column;gap:3px}.podium small{color:var(--at-muted);font-size:7px}.podium strong{font:800 14px 'Arial Narrow',sans-serif}.podium b{color:var(--at-accent);font:800 9px 'SFMono-Regular',monospace}.podium .champion{border-left:2px solid var(--at-accent);padding-left:9px}.atlas-bracket{display:grid;gap:13px;grid-template-columns:repeat(4,1fr);padding-top:29px}.round{border-left:2px solid var(--at-line);padding-left:11px}.round:last-child{border-color:var(--at-accent)}.round header{align-items:baseline;display:flex;justify-content:space-between;margin-bottom:11px}.round header strong{font:800 9px 'SFMono-Regular',monospace}.round header span{color:var(--at-muted);font:7px 'SFMono-Regular',monospace}.match{background:var(--at-surface);border:1px solid var(--at-line);display:grid;gap:4px;grid-template-columns:1fr auto;margin-bottom:8px;padding:8px 9px}.match span{font-size:9px}.match .winner{color:var(--at-accent);font-weight:800}.match b{font:800 9px 'SFMono-Regular',monospace;grid-column:2;grid-row:1/span 2}.match small{color:var(--at-muted);font:7px 'SFMono-Regular',monospace;grid-column:1/-1;text-transform:uppercase}
.markets-heading{padding-bottom:30px}.market-mode{display:flex}.market-mode button{background:transparent;border:1px solid var(--at-line);color:var(--at-muted);font-size:9px;font-weight:800;padding:9px 11px}.market-mode button.active{background:var(--at-accent);border-color:var(--at-accent);color:#fff}.market-overview{display:grid;grid-template-columns:.7fr 1.3fr}.market-feature{align-items:center;background:var(--at-soft);display:flex;flex-direction:column;justify-content:center;min-height:330px;text-align:center}.market-feature>span,.market-feature>small{color:var(--at-muted);font-size:8px}.market-feature>strong{color:var(--at-accent);font:800 50px 'SFMono-Regular',monospace;letter-spacing:-.1em;margin:11px 0 5px}.market-feature .primary-action{margin-top:19px}.market-table{padding:27px 0 27px 27px}.market-table header,.market-table>div{align-items:center;display:grid;gap:12px;grid-template-columns:70px 1fr 65px 15px}.market-table header{border-bottom:1px solid var(--at-line);color:var(--at-muted);font:8px 'SFMono-Regular',monospace;padding-bottom:8px}.market-table>div{border-bottom:1px solid var(--at-line);min-height:54px}.market-table>div>span{color:var(--at-accent);font:800 7px 'SFMono-Regular',monospace}.market-table>div>strong{font-size:10px}.market-table>div>b{font:800 10px 'SFMono-Regular',monospace}.market-table svg{color:var(--at-muted)}
@media(max-width:900px){.atlas-lab{margin:-16px;padding:36px 16px 28px}.lab-header{align-items:start;flex-direction:column;gap:22px}.lab-actions{align-items:start}.portal-nav{grid-template-columns:auto 1fr auto;padding:0 18px}.competition,.portal-nav nav{display:none}.portal-main{padding-left:19px;padding-right:19px}.swarm-strip{grid-template-columns:repeat(3,1fr)}.section-title{grid-column:1/-1;margin-bottom:14px}.agent-tile{margin-bottom:12px}.groups-layout{grid-template-columns:1fr}.predict-heading{grid-template-columns:1fr}.prediction-board{grid-template-columns:1fr 1fr}.consensus-copy{grid-column:1/-1;border-top:1px solid var(--at-line)}.tournament-hero{grid-template-columns:1fr}.tournament-year{position:absolute;right:-10px}.podium{width:72%}.atlas-bracket{overflow-x:auto}.round{min-width:150px}.market-overview{grid-template-columns:1fr}}
@media(max-width:580px){.lab-header h1{font-size:48px}.home-hero{grid-template-columns:1fr;min-height:490px}.hero-copy h2,.screen-heading h2,.predict-heading h2,.tournament-hero h2{font-size:61px}.hero-year{bottom:95px;font-size:210px;position:absolute;right:-18px}.home-metrics{width:100%}.home-modules{grid-template-columns:1fr 1fr}.home-modules button:nth-child(2){border-right:0}.swarm-strip{grid-template-columns:1fr}.agent-tile{border-left:0;border-top:1px solid var(--at-line);padding:9px 0}.screen-heading{align-items:start;flex-direction:column;gap:20px}.group-key{align-items:start}.group-block header,.group-team{grid-template-columns:40px 1fr 45px 35px}.match-selectors{grid-template-columns:1fr 1fr}.match-selectors .primary-action{grid-column:1/-1;justify-content:center}.prediction-board{grid-template-columns:1fr}.prediction-board>div{border-bottom:1px solid var(--at-line);border-right:0}.prediction-evidence{grid-template-columns:1fr;gap:11px}.tournament-hero{min-height:500px}.tournament-year{font-size:210px;position:absolute;right:-10px}.podium{width:100%}.market-mode{align-self:start}.market-table{padding-left:0}.market-table header,.market-table>div{gap:7px;grid-template-columns:55px 1fr 48px 13px}.market-table>div>strong{font-size:9px}}
</style>
