<template>
  <main class="league-view">
    <header class="page-heading"><p class="eyebrow">{{ t('competitions.league.marketsTitle') }}</p><h1>{{ t('competitions.league.marketsTitle') }}</h1><p>{{ t('competitions.league.marketsDescription') }}</p></header>
    <section v-if="loading" class="markets-skeleton" aria-busy="true">
      <article class="result-card market-skeleton-card" aria-hidden="true"><span class="skeleton-heading" /><span class="skeleton-label" /><span class="skeleton-select" /><div class="skeleton-filter-row"><span v-for="filter in 4" :key="filter" /></div><div class="skeleton-market-grid"><span v-for="card in 4" :key="card" /></div></article>
      <article class="result-card market-skeleton-card" aria-hidden="true"><span class="skeleton-heading" /><div class="skeleton-futures-table"><span v-for="row in 6" :key="row" /></div><span class="skeleton-label" /><span class="skeleton-select" /></article>
    </section>
    <section v-else-if="error" class="state-panel state-error" role="alert"><p>{{ error }}</p><button type="button" @click="loadMarkets">{{ t('competitions.league.retry') }}</button></section>
    <template v-else>
      <section class="result-card"><header><h2>{{ t('competitions.league.matchMarkets') }}</h2><span>{{ t('competitions.league.modelImplied') }}</span></header><label for="market-fixture">{{ t('competitions.league.upcomingFixture') }}</label><select id="market-fixture" v-model="selectedFixtureId" @change="loadFixtureMarkets"><option value="">{{ t('competitions.league.selectUpcoming') }}</option><option v-for="fixture in upcomingFixtures" :key="fixture.id" :value="fixture.id">{{ fixture.homeTeam.name }} {{ t('competitions.league.versus') }} {{ fixture.awayTeam.name }} · {{ format(fixture.kickoff) }}</option></select><nav v-if="selectedFixtureId" class="filters" :aria-label="t('markets.filters.label')"><button v-for="filter in filters" :key="filter.key" type="button" :aria-pressed="activeFilter === filter.key" @click="activeFilter = filter.key">{{ filter.label }}</button></nav><p v-if="fixtureLoading">{{ t('competitions.league.loading') }}</p><p v-else-if="fixtureError" class="state-error">{{ fixtureError }}</p><section v-else-if="selectedQuestions.length" class="question-grid"><MarketCard v-for="question in selectedQuestions" :key="question.question_id" :question="question" :show-operator-details="false" /></section><p v-else>{{ t('competitions.league.noMarketFixtures') }}</p></section>
      <section class="result-card"><header><h2>{{ t('competitions.league.seasonFutures') }}</h2><span>{{ t('competitions.league.modelImplied') }}</span></header><table><thead><tr><th scope="col">{{ t('competitions.league.club') }}</th><th scope="col">{{ t('competitions.league.champion') }}</th><th scope="col">{{ t('competitions.league.topFour') }}</th><th scope="col">{{ t('competitions.league.relegation') }}</th></tr></thead><tbody><tr v-for="row in seasonMarkets" :key="row.team.id"><th scope="row">{{ row.team.name }}</th><td>{{ percent(row.championProbability) }}</td><td>{{ percent(row.topFourProbability) }}</td><td>{{ percent(row.relegationProbability) }}</td></tr></tbody></table><label for="season-team">{{ t('competitions.league.selectClub') }}</label><select id="season-team" v-model="selectedSeasonTeamId"><option v-for="row in seasonMarkets" :key="row.team.id" :value="row.team.id">{{ row.team.name }}</option></select><section v-if="selectedSeasonQuestions.length" class="question-grid"><MarketCard v-for="question in selectedSeasonQuestions" :key="question.question_id" :question="question" :show-operator-details="false" /></section><p v-else>{{ t('competitions.league.noProjection') }}</p><p>{{ t('competitions.league.resolution') }}</p></section>
    </template>
  </main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'
import { api } from '../lib/api'
import { leagueApiBase } from '../competition/leagueApi.js'
import MarketCard from '../components/MarketCard.vue'
const { locale, t } = useI18n(); const route = useRoute(); const loading = ref(true); const error = ref(''); const fixtureError = ref(''); const fixtureLoading = ref(false); const seasonMarkets = ref([]); const seasonQuestions = ref([]); const fixtureQuestions = ref([]); const upcomingFixtures = ref([]); const selectedFixtureId = ref(''); const selectedSeasonTeamId = ref(''); const activeFilter = ref('all')
const filters = computed(() => [{ key: 'all', label: t('competitions.league.all') }, { key: 'match_winner', label: t('markets.filters.matchWinner') }, { key: 'draw', label: t('markets.filters.draw') }, { key: 'btts', label: t('markets.filters.btts') }, { key: 'over_under', label: t('markets.filters.overUnder') }, { key: 'clean_sheet', label: t('markets.filters.cleanSheet') }, { key: 'correct_score', label: t('markets.filters.correctScore') }])
const selectedQuestions = computed(() => fixtureQuestions.value.filter((question) => question.tags?.includes(selectedFixtureId.value) && (activeFilter.value === 'all' || question.prop_type === activeFilter.value)))
const selectedSeasonQuestions = computed(() => seasonQuestions.value.filter((question) => question.tags?.includes(selectedSeasonTeamId.value)))
async function loadFixtureMarkets() { if (!selectedFixtureId.value) { fixtureQuestions.value = []; return } fixtureLoading.value = true; fixtureError.value = ''; try { const response = await api.post(`${leagueApiBase(route.params.competitionEditionSlug)}/markets/match`, { fixtureId: selectedFixtureId.value }); fixtureQuestions.value = response.data?.questions || [] } catch (cause) { fixtureError.value = cause.response?.data?.error || t('competitions.league.marketLoadFailed'); fixtureQuestions.value = [] } finally { fixtureLoading.value = false } }
async function loadMarkets() { loading.value = true; error.value = ''; try { const response = await api.get(`${leagueApiBase(route.params.competitionEditionSlug)}/markets`); const payload = response.data || {}; seasonMarkets.value = payload.seasonMarkets || []; seasonQuestions.value = payload.seasonQuestions || []; upcomingFixtures.value = (payload.fixtureMarkets || []).slice(0, 30).map((fixture) => ({ id: fixture.fixture, kickoff: fixture.kickoff, homeTeam: fixture.homeTeam, awayTeam: fixture.awayTeam })); selectedFixtureId.value = upcomingFixtures.value[0]?.id || ''; selectedSeasonTeamId.value = seasonMarkets.value[0]?.team?.id || ''; await loadFixtureMarkets() } catch (cause) { error.value = cause.response?.data?.error || t('competitions.league.marketLoadFailed') } finally { loading.value = false } }
function format(value) { return new Intl.DateTimeFormat(locale.value, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function percent(value) { return new Intl.NumberFormat(locale.value, { style: 'percent', maximumFractionDigits: 1 }).format(Number(value) || 0) }
onMounted(loadMarkets)
</script>

<style scoped>
.league-view { display: grid; gap: var(--space-6); min-width: 0; }.page-heading, .result-card { display: grid; gap: var(--space-3); }.page-heading h1, h2 { font-family: var(--font-family-display); margin: 0; }.page-heading p:last-child, .result-card header span, .result-card > p { color: var(--color-text-muted); margin: 0; }.eyebrow { color: var(--color-accent); font: var(--font-weight-bold) var(--font-size-xs) / 1.2 var(--font-family-data); letter-spacing: .08em; margin: 0; text-transform: uppercase; }.state-panel, .result-card { background: var(--color-surface); border: var(--border-width-thin) solid var(--color-border); padding: var(--space-5); }.state-panel { align-items: center; display: flex; justify-content: space-between; }.state-error { background: var(--color-danger-surface); color: var(--color-danger); }.state-panel p { margin: 0; }button, select { min-height: var(--control-height-lg); padding: 0 var(--space-3); }button { background: var(--color-accent); border: 0; color: var(--color-accent-contrast); cursor: pointer; font-weight: var(--font-weight-semibold); }.filters { border-bottom: var(--border-width-thin) solid var(--color-border); display: flex; flex-wrap: wrap; gap: var(--space-2); padding-bottom: var(--space-3); }.filters button { background: transparent; border-bottom: var(--border-width-strong) solid transparent; color: var(--color-text-muted); }.filters button[aria-pressed="true"] { border-bottom-color: var(--color-accent); color: var(--color-text); }.question-grid { display: grid; gap: var(--space-4); grid-template-columns: repeat(2, minmax(0, 1fr)); }.result-card header { align-items: baseline; display: flex; justify-content: space-between; }table { border-collapse: collapse; text-align: left; width: 100%; }th, td { border-bottom: var(--border-width-thin) solid var(--color-border); padding: var(--space-3) var(--space-2); }@media (max-width: 720px) { .question-grid { grid-template-columns: 1fr; }.result-card header { align-items: start; flex-direction: column; gap: var(--space-2); } }
.result-card > select { appearance: none; background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='%236f6a63' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E"); background-position: right var(--space-4) center; background-repeat: no-repeat; background-size: 1.125rem; padding-right: calc(var(--space-4) + 1.5rem); }
.markets-skeleton { display: grid; gap: var(--space-6); }
.market-skeleton-card { gap: var(--space-4); }
.markets-skeleton span { animation: skeleton-pulse 1.4s ease-in-out infinite; background: var(--color-surface-inset); display: block; }
.skeleton-heading { height: 1.5rem; width: 42%; }
.skeleton-label { height: .8rem; width: 24%; }
.skeleton-select { height: var(--control-height-lg); width: 100%; }
.skeleton-filter-row { border-bottom: var(--border-width-thin) solid var(--color-border); display: flex; gap: var(--space-2); padding-bottom: var(--space-3); }
.skeleton-filter-row span { height: 1.5rem; width: 4.5rem; }
.skeleton-market-grid { display: grid; gap: var(--space-3); grid-template-columns: repeat(2, minmax(0, 1fr)); }
.skeleton-market-grid span { min-height: 7rem; }
.skeleton-futures-table { display: grid; gap: var(--space-3); }
.skeleton-futures-table span { border-bottom: var(--border-width-thin) solid var(--color-border); height: 2rem; }
@keyframes skeleton-pulse { 50% { opacity: .45; } }
@media (prefers-reduced-motion: reduce) { .markets-skeleton span { animation: none; } }
</style>
