<template>
  <div class="legal">
    <h1>Legal Notice</h1>
    <p class="updated">Last updated: June 2026</p>

    <section>
      <h2>1. Nature of Predictions</h2>
      <p>
        SoccerOctopus provides probabilistic predictions generated by a swarm of AI agents
        using statistical models, historical data, team form, and tactical analysis.
        All predictions are <strong>approximations only</strong> and are not guarantees of
        any outcome. Football matches are inherently unpredictable and actual results may
        differ significantly from any prediction made by this platform.
      </p>
    </section>

    <section>
      <h2>2. Not Financial or Betting Advice</h2>
      <p>
        Nothing on SoccerOctopus constitutes financial advice, betting advice, or a
        recommendation to place any wager. Predictions are provided solely as informational
        tools to assist users in forming their own independent judgement. You should never
        bet more than you can afford to lose.
      </p>
    </section>

    <section>
      <h2>3. Limitation of Liability</h2>
      <p>
        SoccerOctopus and its operators accept no responsibility or liability for any
        financial loss, damage, or harm arising directly or indirectly from the use of
        predictions or market estimates published on this platform. Use of this service
        is entirely at your own risk.
      </p>
    </section>

    <section>
      <h2>4. Gambling Regulations</h2>
      <p>
        Betting and gambling may be regulated or prohibited in your jurisdiction. It is
        your sole responsibility to ensure that any betting activity you undertake complies
        with the laws applicable in your country or region. SoccerOctopus does not operate
        as a bookmaker, exchange, or licensed gambling operator.
      </p>
    </section>

    <section>
      <h2>5. Responsible Gambling</h2>
      <p>
        If you or someone you know may have a gambling problem, please seek help.
        Resources include <a href="https://www.begambleaware.org" target="_blank" rel="noopener">BeGambleAware</a>
        and <a href="https://www.ncpgambling.org" target="_blank" rel="noopener">National Council on Problem Gambling</a>.
      </p>
    </section>

    <div class="back">
      <router-link to="/">← Back to Home</router-link>
    </div>
  </div>
</template>

<style scoped>
.legal {
  max-width: 760px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 28px;
}

h1 {
  color: #e2b714;
  font-size: 28px;
}

.updated {
  color: #8888aa;
  font-size: 13px;
  margin-top: -20px;
}

section {
  background: #16213e;
  border: 1px solid #0f3460;
  border-radius: 10px;
  padding: 22px 26px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

h2 {
  color: #a0c0ff;
  font-size: 16px;
  font-weight: 700;
}

p {
  color: #c0c0d8;
  font-size: 14px;
  line-height: 1.7;
}

p strong {
  color: #e0e0e0;
}

a {
  color: #a0c0ff;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

.back {
  font-size: 14px;
}

.back a {
  color: #e2b714;
}
</style>
